---
- name: Restart auto-cpufreq
  ansible.builtin.systemd:
    name: auto-cpufreq
    state: restarted
  become: true

- name: Restart TLP
  ansible.builtin.systemd:
    name: tlp
    state: restarted
  become: true
