# Your User Details

user_name: "{{ vault_user_name }}"

git_name: "{{ vault_git_name }}"

git_email: "{{ vault_git_email }}"

timezone: "America/Los_Angeles"

ansible_become_password: "{{ vault_become_password }}"

workpc_rdp: "{{ vault_workpc_rdp }}"

mainpc_smb_host: "{{ vault_mainpc_smb_host }}"

mainpc_smb_user: "{{ vault_mainpc_smb_user }}"

mainpc_smb_password: "{{ vault_mainpc_smb_password }}"

mainpc_smb_shares: "{{ vault_mainpc_smb_shares }}"

ssh_private_key: "{{ vars['vault_' + ansible_facts['hostname'] + '_ssh_private_key'] }}"

seedbox_host: "{{ vault_seedbox_host }}"

seedbox_user: "{{ vault_seedbox_user }}"

seedbox_name: "{{ vault_seedbox_name }}"
