# Your User Details

user_name: "{{ vault_user_name }}"

git_name: "{{ vault_git_name }}"

git_email: "{{ vault_git_email }}"

timezone: "America/Los_Angeles"

ansible_become_password: "{{ vault_become_password }}"

workpc_rdp: "{{ vault_workpc_rdp }}"
