---
- name: Regenerate GRUB
  ansible.builtin.command:
    cmd: grub-mkconfig -o /boot/grub/grub.cfg
  become: true

- name: Reload NFS exports
  ansible.builtin.command: exportfs -ra
  become: true

- name: Reload NetworkManager connection
  ansible.builtin.command:
    cmd: "nmcli connection up {{ locus_nic }}"
  become: true
  changed_when: true
