---
# --- Initial Pacman Upgrade, EndeavourOS Repos ---

- name: Upgrade Pacman Cache to Current
  community.general.pacman:
    update_cache: true
    upgrade: true

# --- Add CachyOS Repo Keys ---

- name: Import CachyOS GPG Key
  ansible.builtin.command: pacman-key --recv-keys F3B607488DB35A47 --keyserver keyserver.ubuntu.com

- name: Locally Sign CachyOS GPG Key
  ansible.builtin.command: pacman-key --lsign-key F3B607488DB35A47

# --- Preparation to Convert to CachyOS Repo Mirrors ---

- name: Create temporary CachyOS mirrorlist
  ansible.builtin.copy:
    dest: /etc/pacman.d/cachyos-mirrorlist
    content: |
      #Temporary bootstrap mirror
      Server = https://mirror.cachyos.org/repo/$arch/$repo
    mode: '0644'

- name: Create temporary CachyOS V3 mirrorlist
  ansible.builtin.copy:
    dest: /etc/pacman.d/cachyos-v3-mirrorlist
    content: |
      #Temporary bootstrap mirror - Yes, this one is gross. I haven't found a better way yet.
      Server = https://mirror.cachyos.org/repo/x86_64_v3/$repo
    mode: '0644'

- name: Enable CachyOS Repositories in pacman.conf
  ansible.builtin.blockinfile:
    path: /etc/pacman.conf
    insertbefore: "^#?\\[core\\]"
    block: |
      [cachyos]
      Include = /etc/pacman.d/cachyos-mirrorlist

      [cachyos-v3]
      Include = /etc/pacman.d/cachyos-v3-mirrorlist

      [cachyos-core-v3]
      Include = /etc/pacman.d/cachyos-v3-mirrorlist

      [cachyos-extra-v3]
      Include = /etc/pacman.d/cachyos-v3-mirrorlist

- name: Install CachyOS Keyring and Mirrorlists
  community.general.pacman:
    name:
      - cachyos-keyring
      - cachyos-mirrorlist
      - cachyos-v3-mirrorlist
    update_cache: true
    state: present

# --- CachyOS Conversion ---

- name: Allow x86_64-v3 architecture in Pacman
  ansible.builtin.lineinfile:
    path: /etc/pacman.conf
    regexp: '^Architecture = auto'
    line: 'Architecture = auto x86_64_v3'

- name: Convert Pacman Cache to CachyOS
  # Forces Pacman to allow downgrading of packages if called for by newly-added CachyOS mirrors
  ansible.builtin.command: pacman -Syyuu --noconfirm
  register: cachyos_conversion_status
  changed_when: "'there is nothing to do' not in cachyos_conversion_status.stdout"

# --- CachyOS Optimizations ---

- name: Install CachyOS Kernel
  community.general.pacman:
    name:
      - linux-cachyos
      - linux-cachyos-headers
    update_cache: true
    state: present

# --- Final Convergence of Pacman Cache ---

- name: Upgrade Pacman Cache to Current
  community.general.pacman:
    update_cache: true
    upgrade: true

# --- Configure GRUB to boot using CachyOS kernel, and update GRUB if there is a new CachyOS Kernel ---

- name: Set GRUB_DEFAULT to saved
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_DEFAULT='
    line: 'GRUB_DEFAULT=saved'
  when: global_is_x86 | default(false)

- name: Get root partition UUID
  ansible.builtin.command: findmnt -n -o UUID /
  register: cachyos_conversion_root_uuid
  changed_when: false
  when: global_is_x86 | default(false)

- name: Set CachyOS kernel as GRUB default
  ansible.builtin.command: >
    grub-set-default
    'gnulinux-advanced-{{ cachyos_conversion_root_uuid.stdout | trim }}>gnulinux-linux-cachyos-advanced-{{ root_uuid.stdout | trim }}'
  changed_when: true
  when:
    - global_is_x86 | default(false)
    - global_supports_x86_64_v3 | default(false)

- name: Regenerate GRUB config
  ansible.builtin.command: grub-mkconfig -o /boot/grub/grub.cfg
  changed_when: true
